### ISSUE TITLE
Online build is failing - for Android

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1560]
Build is failing on Cloud

### Problem description

ERROR: Failed to trigger build. No further logs

### Expected behavior

Expected to build this. It was building 28 days earlier.

### Environment

- Tabris.js version: "tabris": "2.0.x" - in package.json and latest is chosen in the Cloud build settings

- OS: android build

**Comment by jonek** [comment]
Hi @natanraj we are currently working on a fix and will report back, when the work is finished.
Other users are affected, too.

**Comment by jonek** [comment]
The problem should be fixed now. @natanraj please confirm and close this issue if your build is working again.

**Comment by cookieguru** [comment]
@jonek With 2.x-nightly the build triggers now but gets marked failed before the build actually finishes.  I can click on Detailed Log for the build, and every time I refresh the page there is additional output.  It must have been psycic, because 6 minutes later it failed as so:
```
[./] Replacing variables in config.xml...
[./] Downloading android platform version 2.2.0-dev.20171127...
Unable to download platform: Unexpected status code 404
Warning: Command failed: tabris build android  --debug --device --verbose --cordova-build-config="../../../tabrisBuildConfig.json"
Unable to download platform: Unexpected status code 404
 Use --force to continue.
Aborted due to warnings.
/home/travis/.travis/job_stages: line 961:  4471 Terminated              travis_jigger $! $timeout $cmd
travis_time:end:02023011:start=1511810198919819783,finish=1511810213295739943,duration=14375920160

The command "travis_wait 40 grunt build deploy" exited with 6.
Done. Your build exited with 1.
```

**Comment by mpost** [comment]
We are currently signing of the 2.2.0 release so the nightlies failed accidentally. They will be functional again tomorrow.

**Comment by mpost** [comment]
The nightly is back to normal. Closing this as solved.

**Comment by natanraj** [comment]
I am using latest and still failing. Any help is appreciated

**Comment by cookieguru** [comment]
@natanraj Building with `latest` passes for me, could you post your build log somewhere and link it here?

**Comment by natanraj** [comment]
Looks like the error is  on  - TabrisFirebaseMessagingService.java

and I am using this in my config
 `<plugin name="tabris-plugin-firebase" spec="https://github.com/eclipsesource/tabris-plugin-firebase.git" />`

/home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/android/src/com/eclipsesource/firebase/messaging/TabrisFirebaseMessagingService.java:4: error: cannot find symbol
import android.app.NotificationChannel

**Comment by mpost** [comment]
@natanraj that is because you are consuming the plugin from master which will require a tabris 2.2.0 build. Unless you want to get the latest and greatest you should use a tagged version or from npm.

**Comment by natanraj** [comment]
thanks. it is resolved.
